import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

import LoginPrompt from "../components/LoginPrompt";

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Justin's Chat App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-gray-900 v-screen h-screen flex items-center justify-center">
        <LoginPrompt />
      </div>
    </>
  );
};

export default HomePage;
