import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

import LoginPrompt from "../components/LoginPrompt";

const HomePage: NextPage = () => {
  return (
    <div className="bg-gray-900">
      <Head>
        <title>Justin's Chat App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/llama.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>

      <div
        className="fixed bg-synth bg-cover w-screen h-screen top-0 left-0 z-[0]"
        style={{ opacity: 0.3 }}
      />
      <div className="bg-gray-900 v-screen h-screen flex items-center justify-center z-[-2]">
        <LoginPrompt className="z-[2]" />
      </div>
    </div>
  );
};

export default HomePage;
