import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

import LoginPrompt from "../components/LoginPrompt";

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Justin's Chat App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>

      <div className="bg-gray-900 v-screen h-screen flex items-center justify-center z-[-2]">
        <video
          autoPlay
          muted
          loop
          className="fixed bottom-0 bg-black bg-opacity-[0.5] w-min-[100%] h-min-[100%] scale-[280%]  z-[1]"
          src="/bg.mp4"
        />
        <LoginPrompt className="z-[2]" />
      </div>
    </>
  );
};

export default HomePage;
